version: 2.1

orbs:
  node: circleci/node@5.2.0

executors:
  node:
    docker:
      - image: cimg/node:22.14

jobs:
  test:
    executor: node
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run unit tests
          command: npm test

  docker_build_and_push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "partnerstack" --password-stdin
      - run:
          name: Build and push image
          command: |
            REPO="partnerstack/wrangler-kv-http-emulator"
            GIT_TAG="${CIRCLE_TAG}"
            IMAGE_TAGS=("latest")
            if [ -n "$GIT_TAG" ]; then
              IMAGE_TAGS+=("$GIT_TAG")
            fi
            for TAG in "${IMAGE_TAGS[@]}"; do
              docker build -t "$REPO:$TAG" .
            done
            for TAG in "${IMAGE_TAGS[@]}"; do
              docker push "$REPO:$TAG"
            done

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
  release:
    jobs:
      - docker_build_and_push:
          context:
            - docker-hub
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
